### ISSUE TITLE
syntax error line 7

### ISSUE THREAD

**Issue by nituladaboneko** [ASebastian27/Reddit-Account-Generator#4]
running in linux
$ python3 namesforreddit.py
file "namesforreddit.py", line 7
<!doctype html>
syntaxerror: invalid syntax

**Comment by nituladaboneko** [comment]
ah Firefox saved the .py file as html
used text editor to copy and paste raw text and save

**Comment by nituladaboneko** [comment]
now i get the error in Terminal:
traceback 
file namesforreddit.py line 2 in module
modulenotfounderror: no module named 'selenium'

so i run the readme instructions for requirements (spelled wrong)
$ pip install selenium && pip install webdriver-manager
command 'pip' not found, but there are 18 similar ones.

now what to do?

**Comment by nituladaboneko** [comment]
search online says

Selenium installation is a 3 step process:
1. install Java SDK
2. Install Eclipse
3. Install Selenium Webdriver Files

Is that right?
I ran RAG before on the same linux machine with success and didn't have any of this...

**Comment by ASebastian27** [comment]
Hey, just over one year late. Probably you should've used pip3 😆 
Things have changed around a bit, look around and see if it's useful to you now.
Thanks for showing interest in my project!!
